name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

      - name: Smoke check - uvicorn & streamlit importable
        run: |
          python - <<'PY'
import sys
try:
    import uvicorn
    import streamlit
except Exception as e:
    print("Import failed:", e)
    sys.exit(2)
print("uvicorn and streamlit import OK")
PY

      - name: Syntax check - compile python files
        run: |
          # Check syntax for backend and ui entrypoints (adjust paths if different)
          python -m py_compile app/main.py
          python -m py_compile ui/dashboard.py

      - name: Run unit tests (if present)
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q || ( echo "pytest failed"; exit 1 )
          else
            echo "pytest not installed — skipping tests"
          fi

      # Optional: static analysis (uncomment to enable)
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8 .

